//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvaRodolfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALUNO
    {
        public decimal CPF { get; set; }
        public int MATRICULA { get; set; }
        public string NOME { get; set; }
        public int CURSO_ID { get; set; }
    
        public virtual TBL_CURSO TBL_CURSO { get; set; }
    }
}
